ParksClient/Models/ApiHelper.cs
using System.Threading.Tasks;
using RestSharp;

namespace ParksClient.Models
{
    class ApiHelper
    {
        public static async Task<string> ApiCall()
        {
            RestClient client = new RestClient("http://localhost:5000/api/ParksApi");
            RestRequest request = new RestRequest("/", Method.GET);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task<string> ApiCallParksList(string parks)
        {
            RestClient client = new RestClient("http://localhost:5000/api/ParksApi");
            RestRequest request = new RestRequest($"?parkList={parks}", Method.GET);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

         public static async Task<string> ApiPost(Park park)
        {
            RestClient client = new RestClient("http://localhost:5000/api/ParksApi");
            RestRequest request = new RestRequest("/", Method.POST);
            request.AddJsonBody(park);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task<string> ApiPut(int id, Park park)
        {
            RestClient client = new RestClient("http://localhost:5000/api/ParksApi");
            RestRequest request = new RestRequest($"/{id}", Method.PUT);
            request.AddJsonBody(park);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }
    }
}

ParksClient/Models/Parks.cs
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ParksClient.Models {
    public class Park {
        public int ParkId { get; set; }
        public string Name { get; set; }
        public string Land { get; set; }
        public string State { get; set; }

        public static List<Park> GetParks() 
        {
            var apiCallTask = ApiHelper.ApiCall ();
            var result = apiCallTask.Result;

            JArray jsonResponse = JsonConvert.DeserializeObject<JArray> (result);
            List<Park> parkList = JsonConvert.DeserializeObject<List<Park>>(jsonResponse.ToString());
            return parkList;
        }
    }
}
    

ParksClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using ParksClient.Models;

namespace ParksClient.Controllers
{
    public class HomeController : Controller
    {
     [HttpGet("/")]
        public IActionResult Index()
        {
            var allParks = Park.GetParks();
            return View(allParks);
        }
    }
}

ParksClient/Controllers/ParkController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json;
using ParksClient.Models;

namespace ParksClient.Controllers
{
    public class ParkController : Controller
    {

        
        public ActionResult Details (Park park)
        {
            return View(park);
        }

    }
}

ParksClient/Views/Home/Index.cshtml
@using ParksClient.Models;
@model List<Park>;
<h1>State and National Parks in the SW:</h1>
<p>So far these are in New Mexico and Colorado</p>
<p>Click on each name to see their details. There will be more to come!</p>

<ol>
@foreach (Park park in Model)
{
    <ul>
        <li>@Html.ActionLink(@park.Name, "Details", "Park", new Park {ParkId = park.ParkId, State = park.State, Land = park.Land})</li>
    </ul>
    <br>
}
</ol>

ParksClient/Views/Park/Details.cshtml
@using ParksClient.Models;
@model ParksClient.Models.Park;


<h1>Park Details:</h1>
<ul>
    <li>This is a @Model.Land Park.</li>
    <li>It is in @Model.State</li>
</ul>


<button class="btn btn-info">@Html.ActionLink("Back to List", "Index", "Home")</button>

ParksClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParksData</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - AK
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>